import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";

const iranSans = localFont({
  src: "../../public/fonts/IRANIAN-SANS.woff2",
  variable: "--font-iranSans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={`w-full h-svh ${iranSans.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
